### ISSUE TITLE
Когда на рынок собираетесь выходить с данным продуктом?

### ISSUE THREAD

**Issue by CrystalCharin1** [Qwirik/smart-home-course-project-#1]

**Comment by Qwirik** [comment]
завтра

**Comment by dog12345678** [comment]
посмотрим

**Comment by CrystalCharin1** [comment]
> посмотрим

**Comment by CrystalCharin1** [comment]
> > посмотрим

**Comment by CrystalCharin1** [comment]
> > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > > > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > > > > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > > > > > > посмотрим

**Comment by CrystalCharin1** [comment]
> > > > > > > > > > посмотрим

**Comment by CrystalCharin1** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> завтра
посмотрим

**Comment by CrystalCharin1** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> посмотрим

**Comment by dog12345678** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
